README.md

Added links for the project board and deploying. Found under README.md.
New change.
We need to communicate with other web devs about our progress.
When this merge is accepted, the team can test it by going into github under README.md and select the links.

Added project board and deploy links

---

api/orders.js

Created two functions within orders.js to get all orders and get one single order from the orders array in the firebase
#15  
Adds functionality to pull orders from the firebase to be used on the DOM
import `getOrders` and `getSingleOrder` from `api/orders` and call the functions in a way that their outputs can be viewed

created getOrders and getSingleOrder API calls in orders.js

---

clearDom.js
components/buttons/logoutButton.js
components/navbar.js
events/navigationEvents.js
public/index.html
public/main.js
renderToDom.js
styles/main.scss
styles/navbar.scss
utils/auth.js
utils/sample_data/sampleData.json
utils/viewDirector.js

This PR implements a fully functional navigation bar with proper authentication flow and Bootstrap 5 integration. The changes include:
1. **Navbar Component Updates:**
- Implemented fixed-top navigation with proper content padding
- Added a responsive dropdown menu for Orders section
- Integrated user welcome message
- Positioned logout button correctly
- Added proper logo sizing and styling
2. **Authentication Flow Improvements:**
- Fixed logout button rendering location
- Improved authentication state persistence
- Added proper error handling for auth operations
3. **Styling and Layout:**
- Added body padding to prevent content overlap with fixed navbar
- Implemented consistent logo sizing
- Enhanced mobile responsiveness
1. **Authentication Flow:**
- Log in using Google authentication …

Navbar Enhancement and Authentication Flow Improvements

---

api/order_items.js

wrote 2 API calls in order_items.js
1. getOrderItems
2. getSingleOrderItem
#39 #40

GET order_items API calls (2)

---

pages/homePage.js

Test merge conf

---

pages/homePage.js

test-validate

---

api/order_items.js

2 API calls:
- createOrderItem
- updateOrderItem
-API call to create a new order item
-API call to patch/update an order item
#20, #22
Can be tested later when we use these functions

create order item & update order item

---

api/order_items.js

API Call to delete a single order item
#46 
Can test later when we use this function

Delete order item

---

api/orderItems.js

renamed orderItems file to use camelCase and fixed esLint problems in it

renamed orderItems file to use camelCase and fixed esLint problems in it

---

components/navbar.js

Navbar decided no dropdown

---

clearDom.js
components/navbar.js
renderToDom.js
utils/clearDom.js

Deleted existing clearDom and renderToDom JS
Adjusted navbar rendering.
https://github.com/nss-evening-cohort-29/hhpw-team-elpheba/pull/51/commits/838d9f731edaad919acfdbd62ee023fb22ca2b0c
The file folder structure has been updated with Mike's changes.

Update the file structure

---

pages/ordersPage.js

OrdersPage

---

api/orderItems.js
events/domEvents.js
pages/orderItemsPage.js
pages/ordersPage.js
startApp.js

Order items now appear on the page when you click "details" on an order. If no order items exist yet, "no order items" string shows. In both cases, "add item" and "go to payment" buttons also appear, although neither are functional yet. There is an issue- the top of the content is slightly hidden behind the navbar.
**more specific breakdown of code that was done:**
- updated firebase sample data to be compatible. added firebaseKey's to orders and added the order's firebaseKey's as order_item's order_id. for now, you can test with test google account which has the uid associated with the orders of the updated data. login info below in 'how can this be tested'
- small change in ordersPage.js just changing the buttons to id's instead of classes for destructuring use
- updated orderItemsPage …

order items page view

---

events/navigationEvents.js
pages/revenuePage.js
shared/domBuilder.js
styles/_revenue.scss
styles/main.scss

The changes that were made in this PR include adding content that renders dynamically to the Revenue Overview's page and the basic CSS attributes for that content.
#68

created a skeleton model for the revenue overview page

---

components/navbar.js
events/navigationEvents.js
pages/orderItemsPage.js
shared/domBuilder.js
styles/_loginPage.scss
styles/main.scss
utils/clearDom.js

This pull request introduces several improvements:
- **Background Image Fix:** Consolidated the gradient and background image into a single pseudo-element, removed negative z-indices, and ensured proper SCSS importing to display the login background as intended.
- **Consistent Container Usage:** Removed references to `#view` container and standardized all rendering targets to `#main-container` for improved consistency and maintainability.
- **Refactoring & Cleanup:** Ensured that container-clearing functions are consistently used before rendering new pages, preventing leftover content from persisting when navigating between views.
#71 
1. **Background Check:** Navigate to the login page and ensure that the background image with the gradient overlay is now visible.
2. **Navigation Tests:** …

fix the login design, make sure all pages rendering main-container

---

events/domEvents.js
events/formEvents.js
pages/createOrderItemPage.js
pages/orderItemsPage.js

- Set up event handling to show the form when the "Add Item" button is clicked for a specific order.
- Added functionality for adding order items to a specific order by creating a dynamic form with unique IDs based on the order's Firebase key.
- Updated `formEvents.js` to handle the item submission process, associating the order item with the correct order ID.
#20
- This change enables the addition of items to orders, ensuring that the added items are correctly associated with the right order via the order's Firebase key.
- Test by navigating to the order page and clicking the "Add Item" button.
- Ensure the form appears for adding an item to the order, and on submitting, check if the new item appears with the correct order.

Create Order Items Functionality

---

events/domEvents.js
pages/ordersPage.js
styles/_orders.scss
styles/main.scss

Update the design

---

events/domEvents.js
events/formEvents.js
pages/closeOrderPage.js
styles/_orders.scss

Added new click event handlers and updated the UI to improve the order payment and closing process. This includes implementing features for selecting payment types, choosing tips, and handling error scenarios for missing order data.
#23 
Closing an order with payment type and tip selection.
Navigating to the payment page with proper error handling.
Cancelling payment to display order items again.
Highlighting selected tip buttons and clearing custom tip inputs.
Close Order Workflow:
Click the "Close Order" button.
Select a payment type and tip percentage or enter a custom tip.
Submit and verify the order is closed successfully with accurate data.
Go to Payment:
Click the "Go to Payment" button for an order.
Verify it loads the close order page or displays an error if the order is missing. …

Close Order Page

---

pages/orderItemsPage.js
pages/revenuePage.js
utils/helperFunctions.js

This branch introduces the calculation function that gathers the total cost for all order items associated with a single order. 
This is done by calling this function inside another function, _showOrderItems_, located in orderItemsPage.js. When this process happens, the function _getValues_ goes to the object that it is targeting at the moment on orderItemsPage.js, goes to the key of item_price, turns that value into a number, and adds that number to the total variable in _getValues_. That total variable will pop up at the top of the page when order-items begin to populate the HTML. 
#62 
Devs would need to go to settings in Firebase, go to authorized domains, and copy + paste the deploy preview URL into authorized domains. This all must happen to then utilize the deploy preview link …

Created a function that will update the total for all order-items associated with a single order

---

events/navigationEvents.js
pages/revenuePage.js

**Issue**
When you navigate from the home page to the revenue page and back to the home page, the entire home page is duplicated and will appear at the bottom of the other pages when navigating EXCEPT the revenues page. It will only disappear upon refresh.
**Solution**
This branch fixes this issue by rendering the revenues page to its own container, removing access to it on adminPageEvents.js where it was being rendered to the container admin-dashboard. 
- The content under adminPageEvents.js was left untouched until further development. 
- When having access to the admin-dashboard, it would load up content as a duplicate into the admin-dashboard container as well as the main-container on the home page. 
The use of the _renderToDom_ function was also completely removed from …

Altered code to ensure pages load and clear through nav events

---

api/orders.js
events/domEvents.js
events/formEvents.js
pages/closeOrderPage.js
pages/createOrderItemPage.js
pages/orderItemsPage.js

update, design and logic

---

events/domEvents.js
pages/orderItemsPage.js

-added click event in domEvents to delete orderItem
-added firebaseKey of order to delete button id for access in destructuring, since it is needed to pass into getOrderItems, which is called after deleting
#18
delete an order item
check firebase data to make sure that it is deleted, but also that the corresponding order is _not_ deleted

added delete order items functionality

---

events/formEvents.js
pages/createOrderItemPage.js

fix: Edit Order Item functionality and form handling
- Fixed form ID generation in createOrderItemPage.js to ensure proper format
- Updated formEvents.js to correctly handle order item updates
- Improved error handling for missing form inputs
- Removed unused deleteSingleOrderItem import to fix linting error
- Added proper validation for itemFirebaseKey and orderFirebaseKey
- Enhanced price formatting consistency across updates
This commit resolves the issue where Edit Order Item wasn't working properly
and improves the overall robustness of the form handling system.

Fix the edit order functionlity

---

docs/documents.md

1. [Core Components](#core-components)
2. [Pages and Routing](#pages-and-routing)
3. [State Management](#state-management)
4. [Utility Functions](#utility-functions)
5. [API Integration](#api-integration)
6. [Styles and Theming](#styles-and-theming)
7. [Forms and Validation](#forms-and-validation)
8. [Event Handling](#event-handling)
9. [Authentication](#authentication)
10. [Development Workflow](#development-workflow)

Tech Document

---

components/navbar.js
events/navigationEvents.js
pages/ordersPage.js
pages/revenuePage.js
styles/_orders.scss

fixed the issues
